version: "3.9"

services:
  app:
    build: .
    container_name: biko_app
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - biko
      
  db:
    image: mysql:8.4
    container_name: biko_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - biko

networks:
  biko:
    driver: bridge

volumes:
  dbdata: