services:
  app:
    build: .
    container_name: biko_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - biko

  nginx:
    image: nginx:alpine
    container_name: biko_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - biko

  db:
    image: mysql:8.4
    container_name: biko_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - biko

  reverb:
    build: .
    container_name: biko_reverb
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan reverb:start
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    networks:
      - biko
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: biko_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - biko
    depends_on:
      - db

networks:
  biko:
    driver: bridge

volumes:
  dbdata: